/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AssignPresetDto,
  EventDto,
  EventSummaryDto,
  PublishEventDto,
  UpdateEventDto
} from '../model';

import { customInstance } from '../../common/axios';




export const getActiveEvent = (

 signal?: AbortSignal
) => {


      return customInstance<EventSummaryDto>(
      {url: `/api/events/active`, method: 'GET', signal
    },
      );
    }




export const getGetActiveEventQueryKey = () => {
    return [
    `/api/events/active`
    ] as const;
    }


export const getGetActiveEventQueryOptions = <TData = Awaited<ReturnType<typeof getActiveEvent>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActiveEvent>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetActiveEventQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getActiveEvent>>> = ({ signal }) => getActiveEvent(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getActiveEvent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetActiveEventQueryResult = NonNullable<Awaited<ReturnType<typeof getActiveEvent>>>
export type GetActiveEventQueryError = unknown


export function useGetActiveEvent<TData = Awaited<ReturnType<typeof getActiveEvent>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActiveEvent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getActiveEvent>>,
          TError,
          Awaited<ReturnType<typeof getActiveEvent>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetActiveEvent<TData = Awaited<ReturnType<typeof getActiveEvent>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActiveEvent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getActiveEvent>>,
          TError,
          Awaited<ReturnType<typeof getActiveEvent>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetActiveEvent<TData = Awaited<ReturnType<typeof getActiveEvent>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActiveEvent>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetActiveEvent<TData = Awaited<ReturnType<typeof getActiveEvent>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActiveEvent>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetActiveEventQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getPastEvents = (

 signal?: AbortSignal
) => {


      return customInstance<EventSummaryDto[]>(
      {url: `/api/events`, method: 'GET', signal
    },
      );
    }




export const getGetPastEventsQueryKey = () => {
    return [
    `/api/events`
    ] as const;
    }


export const getGetPastEventsQueryOptions = <TData = Awaited<ReturnType<typeof getPastEvents>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPastEvents>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPastEventsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPastEvents>>> = ({ signal }) => getPastEvents(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPastEvents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPastEventsQueryResult = NonNullable<Awaited<ReturnType<typeof getPastEvents>>>
export type GetPastEventsQueryError = unknown


export function useGetPastEvents<TData = Awaited<ReturnType<typeof getPastEvents>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPastEvents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPastEvents>>,
          TError,
          Awaited<ReturnType<typeof getPastEvents>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPastEvents<TData = Awaited<ReturnType<typeof getPastEvents>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPastEvents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPastEvents>>,
          TError,
          Awaited<ReturnType<typeof getPastEvents>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPastEvents<TData = Awaited<ReturnType<typeof getPastEvents>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPastEvents>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetPastEvents<TData = Awaited<ReturnType<typeof getPastEvents>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPastEvents>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPastEventsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getEventById = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<EventSummaryDto>(
      {url: `/api/events/${id}`, method: 'GET', signal
    },
      );
    }




export const getGetEventByIdQueryKey = (id: string,) => {
    return [
    `/api/events/${id}`
    ] as const;
    }


export const getGetEventByIdQueryOptions = <TData = Awaited<ReturnType<typeof getEventById>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEventByIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEventById>>> = ({ signal }) => getEventById(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEventById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetEventByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getEventById>>>
export type GetEventByIdQueryError = unknown


export function useGetEventById<TData = Awaited<ReturnType<typeof getEventById>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEventById>>,
          TError,
          Awaited<ReturnType<typeof getEventById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEventById<TData = Awaited<ReturnType<typeof getEventById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEventById>>,
          TError,
          Awaited<ReturnType<typeof getEventById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEventById<TData = Awaited<ReturnType<typeof getEventById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetEventById<TData = Awaited<ReturnType<typeof getEventById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventById>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetEventByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const updateEvent = (
    id: string,
    updateEventDto: UpdateEventDto,
 signal?: AbortSignal
) => {


      return customInstance<EventDto>(
      {url: `/api/events/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateEventDto, signal
    },
      );
    }



export const getUpdateEventMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateEvent>>, TError,{id: string;data: UpdateEventDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateEvent>>, TError,{id: string;data: UpdateEventDto}, TContext> => {

const mutationKey = ['updateEvent'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateEvent>>, {id: string;data: UpdateEventDto}> = (props) => {
          const {id,data} = props ?? {};

          return  updateEvent(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateEventMutationResult = NonNullable<Awaited<ReturnType<typeof updateEvent>>>
    export type UpdateEventMutationBody = UpdateEventDto
    export type UpdateEventMutationError = unknown

    export const useUpdateEvent = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateEvent>>, TError,{id: string;data: UpdateEventDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateEvent>>,
        TError,
        {id: string;data: UpdateEventDto},
        TContext
      > => {
      return useMutation(getUpdateEventMutationOptions(options), queryClient);
    }
    export const deleteEvent = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/events/${id}`, method: 'DELETE', signal
    },
      );
    }



export const getDeleteEventMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteEvent>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteEvent>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteEvent'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteEvent>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteEvent(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteEventMutationResult = NonNullable<Awaited<ReturnType<typeof deleteEvent>>>

    export type DeleteEventMutationError = unknown

    export const useDeleteEvent = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteEvent>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteEvent>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteEventMutationOptions(options), queryClient);
    }
    export const publishEvent = (
    publishEventDto: PublishEventDto,
 signal?: AbortSignal
) => {


      return customInstance<EventDto>(
      {url: `/api/events/publish`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: publishEventDto, signal
    },
      );
    }



export const getPublishEventMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof publishEvent>>, TError,{data: PublishEventDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof publishEvent>>, TError,{data: PublishEventDto}, TContext> => {

const mutationKey = ['publishEvent'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof publishEvent>>, {data: PublishEventDto}> = (props) => {
          const {data} = props ?? {};

          return  publishEvent(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PublishEventMutationResult = NonNullable<Awaited<ReturnType<typeof publishEvent>>>
    export type PublishEventMutationBody = PublishEventDto
    export type PublishEventMutationError = unknown

    export const usePublishEvent = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof publishEvent>>, TError,{data: PublishEventDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof publishEvent>>,
        TError,
        {data: PublishEventDto},
        TContext
      > => {
      return useMutation(getPublishEventMutationOptions(options), queryClient);
    }
    export const assignEventPreset = (
    id: string,
    assignPresetDto: AssignPresetDto,
 signal?: AbortSignal
) => {


      return customInstance<EventDto>(
      {url: `/api/events/${id}/preset`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: assignPresetDto, signal
    },
      );
    }



export const getAssignEventPresetMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assignEventPreset>>, TError,{id: string;data: AssignPresetDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof assignEventPreset>>, TError,{id: string;data: AssignPresetDto}, TContext> => {

const mutationKey = ['assignEventPreset'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof assignEventPreset>>, {id: string;data: AssignPresetDto}> = (props) => {
          const {id,data} = props ?? {};

          return  assignEventPreset(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AssignEventPresetMutationResult = NonNullable<Awaited<ReturnType<typeof assignEventPreset>>>
    export type AssignEventPresetMutationBody = AssignPresetDto
    export type AssignEventPresetMutationError = unknown

    export const useAssignEventPreset = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assignEventPreset>>, TError,{id: string;data: AssignPresetDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof assignEventPreset>>,
        TError,
        {id: string;data: AssignPresetDto},
        TContext
      > => {
      return useMutation(getAssignEventPresetMutationOptions(options), queryClient);
    }
    export const rerollEventPin = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<EventDto>(
      {url: `/api/events/${id}/pin/reroll`, method: 'POST', signal
    },
      );
    }



export const getRerollEventPinMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rerollEventPin>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof rerollEventPin>>, TError,{id: string}, TContext> => {

const mutationKey = ['rerollEventPin'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof rerollEventPin>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  rerollEventPin(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RerollEventPinMutationResult = NonNullable<Awaited<ReturnType<typeof rerollEventPin>>>

    export type RerollEventPinMutationError = unknown

    export const useRerollEventPin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rerollEventPin>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof rerollEventPin>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getRerollEventPinMutationOptions(options), queryClient);
    }
    export const activateEvent = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<EventDto>(
      {url: `/api/events/${id}/activate`, method: 'POST', signal
    },
      );
    }



export const getActivateEventMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activateEvent>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof activateEvent>>, TError,{id: string}, TContext> => {

const mutationKey = ['activateEvent'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof activateEvent>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  activateEvent(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ActivateEventMutationResult = NonNullable<Awaited<ReturnType<typeof activateEvent>>>

    export type ActivateEventMutationError = unknown

    export const useActivateEvent = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activateEvent>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof activateEvent>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getActivateEventMutationOptions(options), queryClient);
    }
