/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */
import type { VariantDto } from './variantDto';

export interface CreateFoodDto {
  name: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  imageUrl?: string | null;
  categoryId: string;
  variants?: VariantDto[];
  /** Set to false for joke/gag menu items: guests can still order them and see a price, but they are excluded from table/split totals. */
  shouldCalculate?: boolean;
  /** Staff pick: shows a recommended tag next to this food across the menu. */
  isRecommended?: boolean;
  /** Locale the name/description/variant labels are written in */
  lang?: string;
}
