/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */

export interface CreateFeedbackDto {
  by?: string;
  content?: string;
  /** Storage key of an attached image */
  imageUrl?: string;
}
