/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */
import type { FoodVariantDto } from './foodVariantDto';

export interface FoodDetailDto {
  id: string;
  name: string;
  /** @nullable */
  imageUrl: string | null;
  /** @nullable */
  description: string | null;
  /** @nullable */
  categoryId: string | null;
  isAvailable: boolean;
  /** Whether orders of this food count toward table/split totals. False for joke/gag menu items that still show a price and can be ordered, but are free. */
  shouldCalculate: boolean;
  isPopular: boolean;
  /** Staff pick: admins flag this food as recommended so the menu shows a recommended tag. */
  isRecommended: boolean;
  variants: FoodVariantDto[];
  aiTranslationFailed?: boolean;
}
