/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */
import type { GetFoodsSortBy } from './getFoodsSortBy';
import type { GetFoodsSortOrder } from './getFoodsSortOrder';

export type GetFoodsParams = {
sortBy?: GetFoodsSortBy;
sortOrder?: GetFoodsSortOrder;
popular?: boolean;
recommended?: boolean;
category?: string;
count?: number;
page?: number;
lang?: string;
};
