/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */
import type { OrderSplitDto } from './orderSplitDto';

export interface OrderResponseDto {
  id: string;
  tableId: string;
  variantId: string;
  foodId: string;
  /** @nullable */
  eventId: string | null;
  quantity: number;
  price: number;
  currency: string;
  splitAll: boolean;
  foodName: string;
  variantLabel: string;
  /** @nullable */
  foodImageUrl: string | null;
  /** Whether this order counts toward table/split totals. False for joke/gag menu items. */
  shouldCalculate: boolean;
  splits: OrderSplitDto[];
  createdAt: string;
  updatedAt: string;
}
