/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */
import type { NoteResponseDto } from './noteResponseDto';

export interface PersonDto {
  id: string;
  name: string;
  /** @nullable */
  tableId?: string | null;
  /** @nullable */
  eventId?: string | null;
  /** @nullable */
  pfpUrl?: string | null;
  personalNotes?: NoteResponseDto[];
}
