/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */

export interface UpdatePersonPfpDto {
  /**
     * Storage key of the profile picture, or null to clear
     * @nullable
     */
  pfpUrl?: string | null;
}
