/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */

export interface UpdateFoodDto {
  name?: string;
  /** @nullable */
  description?: string | null;
  /**
     * Storage key of the image, or null to clear
     * @nullable
     */
  imageUrl?: string | null;
  categoryId?: string;
  isAvailable?: boolean;
  /** Set to false for joke/gag menu items: guests can still order them and see a price, but they are excluded from table/split totals. */
  shouldCalculate?: boolean;
  /** Staff pick: shows a recommended tag next to this food across the menu. */
  isRecommended?: boolean;
  /** Locale the name/description are written in */
  lang?: string;
}
