/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */

export interface UpdateTableDetailsDto {
  name?: string;
  /**
     * Person id hosting this table, or null to clear
     * @nullable
     */
  tableLeaderId?: string | null;
  /**
     * Storage key of the table banner image, or null to clear
     * @nullable
     */
  bannerUrl?: string | null;
}
