/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateFeedbackDto,
  FeedbackItemDto,
  FeedbackReactionDto,
  GetFeedbackByEventParams,
  GetFeedbackParams,
  GetFeedbackResponseDto,
  ReactDto
} from '../model';

import { customInstance } from '../../common/axios';




export const getFeedback = (
    params?: GetFeedbackParams,
 signal?: AbortSignal
) => {


      return customInstance<GetFeedbackResponseDto>(
      {url: `/api/feedback`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetFeedbackQueryKey = (params?: GetFeedbackParams,) => {
    return [
    `/api/feedback`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetFeedbackQueryOptions = <TData = Awaited<ReturnType<typeof getFeedback>>, TError = unknown>(params?: GetFeedbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeedback>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFeedbackQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFeedback>>> = ({ signal }) => getFeedback(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFeedback>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFeedbackQueryResult = NonNullable<Awaited<ReturnType<typeof getFeedback>>>
export type GetFeedbackQueryError = unknown


export function useGetFeedback<TData = Awaited<ReturnType<typeof getFeedback>>, TError = unknown>(
 params: undefined |  GetFeedbackParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeedback>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFeedback>>,
          TError,
          Awaited<ReturnType<typeof getFeedback>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFeedback<TData = Awaited<ReturnType<typeof getFeedback>>, TError = unknown>(
 params?: GetFeedbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeedback>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFeedback>>,
          TError,
          Awaited<ReturnType<typeof getFeedback>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFeedback<TData = Awaited<ReturnType<typeof getFeedback>>, TError = unknown>(
 params?: GetFeedbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeedback>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetFeedback<TData = Awaited<ReturnType<typeof getFeedback>>, TError = unknown>(
 params?: GetFeedbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeedback>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFeedbackQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const createFeedback = (
    createFeedbackDto: CreateFeedbackDto,
 signal?: AbortSignal
) => {


      return customInstance<FeedbackItemDto>(
      {url: `/api/feedback`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createFeedbackDto, signal
    },
      );
    }



export const getCreateFeedbackMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFeedback>>, TError,{data: CreateFeedbackDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createFeedback>>, TError,{data: CreateFeedbackDto}, TContext> => {

const mutationKey = ['createFeedback'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createFeedback>>, {data: CreateFeedbackDto}> = (props) => {
          const {data} = props ?? {};

          return  createFeedback(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateFeedbackMutationResult = NonNullable<Awaited<ReturnType<typeof createFeedback>>>
    export type CreateFeedbackMutationBody = CreateFeedbackDto
    export type CreateFeedbackMutationError = unknown

    export const useCreateFeedback = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFeedback>>, TError,{data: CreateFeedbackDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createFeedback>>,
        TError,
        {data: CreateFeedbackDto},
        TContext
      > => {
      return useMutation(getCreateFeedbackMutationOptions(options), queryClient);
    }
    export const getFeedbackByEvent = (
    params: GetFeedbackByEventParams,
 signal?: AbortSignal
) => {


      return customInstance<GetFeedbackResponseDto>(
      {url: `/api/feedback/event`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetFeedbackByEventQueryKey = (params?: GetFeedbackByEventParams,) => {
    return [
    `/api/feedback/event`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetFeedbackByEventQueryOptions = <TData = Awaited<ReturnType<typeof getFeedbackByEvent>>, TError = unknown>(params: GetFeedbackByEventParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeedbackByEvent>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFeedbackByEventQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFeedbackByEvent>>> = ({ signal }) => getFeedbackByEvent(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFeedbackByEvent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFeedbackByEventQueryResult = NonNullable<Awaited<ReturnType<typeof getFeedbackByEvent>>>
export type GetFeedbackByEventQueryError = unknown


export function useGetFeedbackByEvent<TData = Awaited<ReturnType<typeof getFeedbackByEvent>>, TError = unknown>(
 params: GetFeedbackByEventParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeedbackByEvent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFeedbackByEvent>>,
          TError,
          Awaited<ReturnType<typeof getFeedbackByEvent>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFeedbackByEvent<TData = Awaited<ReturnType<typeof getFeedbackByEvent>>, TError = unknown>(
 params: GetFeedbackByEventParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeedbackByEvent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFeedbackByEvent>>,
          TError,
          Awaited<ReturnType<typeof getFeedbackByEvent>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFeedbackByEvent<TData = Awaited<ReturnType<typeof getFeedbackByEvent>>, TError = unknown>(
 params: GetFeedbackByEventParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeedbackByEvent>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetFeedbackByEvent<TData = Awaited<ReturnType<typeof getFeedbackByEvent>>, TError = unknown>(
 params: GetFeedbackByEventParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeedbackByEvent>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFeedbackByEventQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const reactToFeedback = (
    id: string,
    reactDto: ReactDto,
 signal?: AbortSignal
) => {


      return customInstance<FeedbackReactionDto>(
      {url: `/api/feedback/${id}/react`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: reactDto, signal
    },
      );
    }



export const getReactToFeedbackMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reactToFeedback>>, TError,{id: string;data: ReactDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof reactToFeedback>>, TError,{id: string;data: ReactDto}, TContext> => {

const mutationKey = ['reactToFeedback'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof reactToFeedback>>, {id: string;data: ReactDto}> = (props) => {
          const {id,data} = props ?? {};

          return  reactToFeedback(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ReactToFeedbackMutationResult = NonNullable<Awaited<ReturnType<typeof reactToFeedback>>>
    export type ReactToFeedbackMutationBody = ReactDto
    export type ReactToFeedbackMutationError = unknown

    export const useReactToFeedback = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reactToFeedback>>, TError,{id: string;data: ReactDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof reactToFeedback>>,
        TError,
        {id: string;data: ReactDto},
        TContext
      > => {
      return useMutation(getReactToFeedbackMutationOptions(options), queryClient);
    }
    export const deleteFeedback = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/feedback/${id}`, method: 'DELETE', signal
    },
      );
    }



export const getDeleteFeedbackMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFeedback>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteFeedback>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteFeedback'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteFeedback>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteFeedback(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteFeedbackMutationResult = NonNullable<Awaited<ReturnType<typeof deleteFeedback>>>

    export type DeleteFeedbackMutationError = unknown

    export const useDeleteFeedback = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFeedback>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteFeedback>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteFeedbackMutationOptions(options), queryClient);
    }
